sudo: required
services:
  - docker

before_install:
  - docker build -t rgnc -f Dockerfile.dev .

script:
  - docker run -p 8050:8050 rgnc
  # - docker run -e CI=true ianodad/react-devops npm run test -- --coverage


language: minimal 
deploy:
  provider: elasticbeanstalk
  region: "eu-east-1"
  app: "Ragnaroc"
  env: "Ragnaroc-env"
  bucket_name: "elasticbeanstalk-us-east-1-285005130642"
  bucket_path: "2022145dJJ-ragnaroc_v22.zip"
  on:
    branch: dev
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"