FROM python:3.8

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
COPY . ./

CMD python setup.py build_ext --inplace



#do the cython commands here and retrieve the file
# python setup.py build_ext --inplace
